name: dottorrent-cli

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
      comment:
        required: true
      url:
        required: true
      file_name:
        required: true

jobs:
  create_torrent:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget
          pipx install dottorrent-cli

      - name: Download file
        run: |
          wget \
          --tries=100 \
          --timeout=30 \
          --read-timeout=30 \
          -O "${{ inputs.file_name }}" \
          "${{ inputs.url }}"

      - name: Create torrent
        run: |
          dottorrent \
          --piece-size 16M \
          --web_seed "${{ inputs.url }}" \
          --comment "${{ inputs.comment }}" \
          "${{ inputs.file_name }}" \
          "${{ inputs.name }}.torrent"

      - name: Upload torrent
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.name }}.torrent
          compression-level: 0
